#!/usr/bin/with-contenv bash
# vim:ft=bash

# Set paths
original_dirs_json="/app/calibre-web-automated/dirs.json"
override_dirs_json="/custom/dirs.json"
app_db="/config/app.db"
empty_metadata_db="$(jq -r '.calibre_library_dir' "$original_dirs_json")/metadata.db"

# Get the Calibre library directory from the override file.
# Make sure this directory exists.
calibre_library_dir=$(jq -r '.calibre_library_dir' "$override_dirs_json")

# If CALIBRE_LIBRARY_DIR is set, use it instead.
if [[ -n "${CALIBRE_LIBRARY_DIR}" ]]; then
  echo "[update-library] Using CALIBRE_LIBRARY_DIR: ${CALIBRE_LIBRARY_DIR}"
  calibre_library_dir="${CALIBRE_LIBRARY_DIR:-$calibre_library_dir}"
  jq --arg dir "$calibre_library_dir" '.calibre_library_dir = $dir' "$original_dirs_json" >"$override_dirs_json"
fi

echo "[update-library] Ensure calibre library directory $calibre_library_dir exists"
install -d -o abc -g abc "$calibre_library_dir"

# If an override file exists, use it.
if [[ -f "$override_dirs_json" ]]; then
  echo "[update-library] Overwriting $original_dirs_json with $override_dirs_json"
  cp -f "$override_dirs_json" "$original_dirs_json"
else
  echo "[update-library] $override_dirs_json not found. Skipping overwrite."
fi

# Check for metadata.db in the new library. Copy it if it's missing.
if [[ ! -f "${calibre_library_dir}/metadata.db" ]]; then
  echo "[update-library] No metadata.db found in new library. Copying from original."
  if [[ -f "$empty_metadata_db" ]]; then
    cp "$empty_metadata_db" "${calibre_library_dir}/metadata.db"
    echo "[update-library] metadata.db copied."
  else
    echo "[update-library] Original metadata.db not found. Cannot copy."
  fi
else
  echo "[update-library] metadata.db already exists in new library. Skipping copy."
fi

# Update the library path in the database.
echo "[update-library] Updating library path with sqlite."
sqlite3 "$app_db" "UPDATE settings SET config_calibre_dir='${calibre_library_dir}';" || echo "[update-library] sqlite error"
echo "[update-library] Library updated and overwrite completed."
