#!/usr/bin/with-contenv bash
# vim:ft=bash

original_dirs_json="/app/calibre-web-automated/dirs.json"
override_dirs_json="/custom/dirs.json"

original_auto_library="/app/calibre-web-automated/scripts/auto_library.py"
override_auto_library="/custom/auto_library.py"

# Overwrite dirs.json
if [ -f "$override_dirs_json" ]; then
  echo "[orverwrite-files] Overwriting $original_dirs_json with $override_dirs_json"
  cp -f "$override_dirs_json" "$original_dirs_json"
else
  echo "[orverwrite-files] $override_dirs_json not found, skipping overwrite"
fi

install -d -o abc -g abc /config/calibre-library

# Overwrite auto_library.py
echo "[orverwrite-files] Overwriting auto_library.py"
cp -f $override_auto_library $original_auto_library

echo "[orverwrite-files] Overwrite completed successfully"
